name: Pages CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    name: Build and deploy HTML
    runs-on: ubuntu-latest
    steps:
      - name: Fetching sources from repository
        uses: actions/checkout@v2
      - name: Setting up Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Installing dependencies
        run: |
          pip install --upgrade pip
          pip install sphinx
      - name: Building HTML using Sphinx
        run: |
          make html
        env:
          CI_ACTION: '1'
      - name: Deploying built HTML to GitHub pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/html
